name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
          # 从仓库的 secret 获取值
          registry: registry.cn-chengdu.aliyuncs.com
          username: wangchch5
          password: wangchch8182
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
        file: highgo-exporter/Dockerfile-arm
        platforms: linux/arm64
        push: true
        tags: registry.cn-chengdu.aliyuncs.com/wangchch/highgo-exporter:1.0.0-arm64
      
