name: Alpine with jre Docker Image CI
on:
  push:
    paths:
      - 'alpine-jre/**'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
          # 从仓库的 secret 获取值
          registry: registry.cn-chengdu.aliyuncs.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
        file: alpine-jre/Dockerfile
        context: ./alpine-jre
        platforms: linux/arm64
        push: true
        tags: registry.cn-chengdu.aliyuncs.com/wangchch/alpine-with-jre:jre17.0.13-arm64
      
