name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: ["Dockerfile"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
          # 从仓库的 secret 获取值
          registry: registry.cn-chengdu.aliyuncs.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
        file: Dockerfile
        context: .
        push: true
        tags: registry.cn-chengdu.aliyuncs.com/wangchch/gisapplication:11.3.0-amd64
